sonar.projectKey=SAP_terraform-btp-sap-btp-role-collection-assignments
sonar.organization=sap-1
sonar.projectName=terraform-btp-sap-btp-role-collection-assignments
sonar.sources=.
sonar.exclusions=**/.terraform/**,**/examples/**,**/*.tfstate,**/*.tfstate.backup
sonar.tests=tests
sonar.test.inclusions=tests/*.tftest.hcl
