name: Terraform Test

# This GitHub action will run on pull requests and pushes on main branch.
# It will run terraform validate and terraform test.
# If there are any errors, it will fail the action and ask the contributor to fix the errors.

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: latest
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Test
        run: terraform test
